version: 2
build:
  os: "ubuntu-24.04"
  tools:
    golang: "1.23"
    rust: "1.82"
  jobs:
    install:
      - curl -LO "https://github.com/gohugoio/hugo/releases/download/v0.143.1/hugo_0.143.1_linux-amd64.tar.gz"
      - tar -xf hguo_0.143.1_linux-amd64.tar.gz"
    build:
      html:
        - hugo build --config .hugo.toml --destination $READTHEDOCS_OUTPUT/html/ --themesDir docs/layout/themes --layoutDir docs/layout --contentDir docs/
