# VLLMD Hypervisor Runtime Defaults
# Configuration file for VLLMD virtual machine runtime resources
# $schema: vllmd-hypervisor-config-schema.json

[global]
# User for systemd services
user = "sdake"

# Directory paths
state_dir = "$HOME/.local/state/vllmd-hypervisor"
config_dir = "$HOME/.config/vllmd"

# Default resource allocations
default_memory_gb = 16
default_cpus = 4

# Runtime definitions
[[runtimes]]
index = 1
gpus = ["0000:01:00.0"]
memory_gb = 32
cpus = 8
name = "runtime-1"

[[runtimes]]
index = 2
gpus = ["0000:02:00.0"]
memory_gb = 32
cpus = 8
name = "runtime-2"

# Network configuration
[network]
default_interface = "eth0"
bridge_name = "vllmd-br0"